### ISSUE TITLE
TwitchNotifier crashes in Funtoo

### ISSUE THREAD

**Issue by Hund** [GiedriusS/TwitchNotifier#4]
I'm running Funtoo with:

* Python 3.4.6
* dev-python/requests 2.13.0
* dev-python/pygobject 3.20.1
* x11-libs/libnotify 0.7.6

And when I run `twitchnotifier -c <username>` I get this:

```
Traceback (most recent call last):
  File "/home/johan/git/TwitchNotifier/twitchnotifier", line 10, in <module>
    import libtn
  File "/home/johan/git/TwitchNotifier/libtn.py", line 11, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib64/python3.4/site-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

**Comment by GiedriusS** [comment]
Hello. Sorry for a late reply. I am not familiar with Gentoo/Funtoo but I think that you may need the introspection USE flag on libnotify. Do you have it enabled? If not, could you enable it, rebuild and see if that namespace becomes available?

**Comment by Hund** [comment]
Np! :) A few thinga have changed since last time. I went back to Gentoo and I'm now using `x11-libs/libtinynotify` instead. The package `x11-libs/libnotify` requires GTK3. :| I still have the same issue though.

But in Funtoo I did use the USE-flag `introspection` with the package `x11-libs/libnotify`.

**Comment by GiedriusS** [comment]
Hmm... do you have a file in `/usr/lib/girepository-1.0/Notify-0.7.typelib` on your system? It should have came with `x11-libs/libnotify`.

**Comment by Hund** [comment]
I don't. `locate` couldnt find it anywere either. :(

**Comment by GiedriusS** [comment]
According to http://www.portagefilelist.de/site/query/listPackageFiles/?category=x11-libs&package=libnotify&version=0.7.7 it should be on your system. I came to the conclusion that this is the key file that you are missing because Debian people apparently have to install a package named `gir1.2-notify-0.7` which contains that file to fix this issue. Could you reinstall `x11-libs/libnotify`?

**Comment by Hund** [comment]
I really don't want to install libnotify, it has gtk3 as a dependency. :/ Isnt't it possible to rely or use notify-send as an alternative? Notifications with other programs works just fine.

**Comment by Hund** [comment]
I installed libnotify and it works, so I'm closing this one. :)
