### ISSUE TITLE
ModuleNotFoundError: No module named 'libtn'

### ISSUE THREAD

**Issue by hringriin** [GiedriusS/TwitchNotifier#5]
```
>$ twitchnotifier -c ${aUserName} -n
Traceback (most recent call last):
  File "/usr/bin/twitchnotifier", line 10, in <module>
    import libtn
ModuleNotFoundError: No module named 'libtn'
```

I'm sorry, I cannot provide further information without help where to look for it.

**Comment by GiedriusS** [comment]
What installation method have you used: the Void Linux package or the AUR one?

**Comment by hringriin** [comment]
I used the AUR package.

This is awkward, I just tried to install it again by hand (AUR package, but without any AUR-helper) and it works now ...

I'm sorry!

**Comment by Hund** [comment]
A rebuild of a Python package may be required when its shared library dependencies are updated in Arch. I don't know why, but some Arch dev said so when he spewed their regular hate against all the AUR helpers.

**Comment by hringriin** [comment]
I will pay attention to that. Thank you!
